# Generated by Django 5.2.4 on 2025-07-10 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RunSQL("""
                          INSERT INTO store_collection (title)
                          VALUES ('Collection');
                          """,
                          """
                          DELETE FROM store_collection
                          WHERE title = 'Collection';
                          """)
    ]
